use ejmcdbstg;

CREATE TABLE CHANNELS 
    ( 
     CHANNEL_ID CHARACTER(6) NOT NULL , 
     CHANNEL_DESC CHARACTER (20)  NOT NULL , 
     CHANNEL_CLASS CHARACTER (20)  NOT NULL , 
     CHANNEL_CLASS_ID CHARACTER(6) NOT NULL 
    )
;


CREATE TABLE COUNTRIES 
    ( 
     COUNTRY_ID CHARACTER(6) NOT NULL , 
     COUNTRY_NAME CHARACTER (40)  NOT NULL , 
     COUNTRY_REGION CHARACTER (20)  NOT NULL , 
     COUNTRY_REGION_ID CHARACTER(6)  NOT NULL 
    ) 
;



CREATE TABLE CUSTOMERS 
    ( 
     CUST_ID CHARACTER(6)  NOT NULL , 
     CUST_FIRST_NAME CHARACTER (20)  NOT NULL , 
     CUST_LAST_NAME CHARACTER (40)  NOT NULL , 
     CUST_GENDER CHAR (1)  NOT NULL , 
     CUST_YEAR_OF_BIRTH CHARACTER (4)  NOT NULL , 
     CUST_MARITAL_STATUS CHARACTER (20) , 
     CUST_STREET_ADDRESS CHARACTER (40)  NOT NULL , 
     CUST_POSTAL_CODE CHARACTER (10)  NOT NULL , 
     CUST_CITY CHARACTER (30)  NOT NULL , 
     CUST_STATE_PROVINCE CHARACTER (40)  NOT NULL , 
     COUNTRY_ID CHARACTER (6)  NOT NULL , 
     CUST_MAIN_PHONE_NUMBER CHARACTER (25)  NOT NULL , 
     CUST_INCOME_LEVEL CHARACTER (30) , 
     CUST_CREDIT_LIMIT CHARACTER (6), 
     CUST_EMAIL CHARACTER (30)
    )
;

CREATE TABLE PRODUCTS 
    ( 
     PROD_ID CHARACTER (6)  NOT NULL , 
     PROD_NAME CHARACTER (50 )  NOT NULL , 
     PROD_DESC TEXT (4000 )  NOT NULL , 
     PROD_CATEGORY CHARACTER (50 )  NOT NULL , 
     PROD_CATEGORY_ID CHARACTER (6)  NOT NULL , 
     PROD_CATEGORY_DESC TEXT (2000 )  NOT NULL , 
     PROD_WEIGHT_CLASS CHARACTER (3)  NOT NULL , 
     SUPPLIER_ID CHARACTER (6)  NOT NULL , 
     PROD_STATUS CHARACTER (20 )  NOT NULL , 
     PROD_LIST_PRICE CHARACTER (10)  NOT NULL , 
     PROD_MIN_PRICE CHARACTER (10)  NOT NULL 
    )
;


CREATE TABLE PROMOTIONS 
    ( 
     PROMO_ID CHARACTER (6)  NOT NULL , 
     PROMO_NAME CHARACTER (30)  NOT NULL , 
     PROMO_COST CHARACTER (12)  NOT NULL , 
     PROMO_BEGIN_DATE CHARACTER(9)  NOT NULL , 
     PROMO_END_DATE CHARACTER(9)  NOT NULL 
    )
;



CREATE TABLE SALES 
    ( 
     PROD_ID CHARACTER (6)  NOT NULL , 
     CUST_ID CHARACTER (6) NOT NULL , 
     TIME_ID CHARACTER (9) NOT NULL , 
     CHANNEL_ID CHARACTER (6) NOT NULL , 
     PROMO_ID CHARACTER (6)  NOT NULL , 
     QUANTITY_SOLD CHARACTER (12)  NOT NULL , 
     AMOUNT_SOLD CHARACTER (12)  NOT NULL 
    ) 
;

CREATE TABLE TIMES 
    ( 
     TIME_ID CHARACTER (9) NOT NULL , 
     DAY_NAME CHARACTER (9 )  NOT NULL , 
     DAY_NUMBER_IN_WEEK CHARACTER (1)  NOT NULL , 
     DAY_NUMBER_IN_MONTH CHARACTER (2)  NOT NULL , 
     CALENDAR_WEEK_NUMBER CHARACTER (2)  NOT NULL , 
     CALENDAR_MONTH_NUMBER CHARACTER (2)  NOT NULL , 
     CALENDAR_MONTH_DESC CHARACTER (8 )  NOT NULL , 
     END_OF_CAL_MONTH CHARACTER (9) NOT NULL , 
     CALENDAR_MONTH_NAME CHARACTER (9 )  NOT NULL DEFAULT(''), 
     CALENDAR_QUARTER_DESC CHARACTER (7 )  NOT NULL , 
     CALENDAR_YEAR CHARACTER (4)  NOT NULL 
    ) 
;
